workflows:
  version: 2
  deploy:
    jobs:
      - build

executors:
  executor:
    docker:
      - image: cimg/node:16.13

version: 2.1
orbs:
  node: circleci/node@4.1
  slack: circleci/slack@4.10.1

jobs:
  build:
    executor: executor
    steps:
      - checkout
      - run: echo VITE_BUILD_BRANCH = ${CIRCLE_BRANCH} > .env
      - run: echo VITE_BUILD_HASH = ${CIRCLE_SHA1} >> .env
      - run: cat .env
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - run: sudo apt-get update && sudo apt-get install rsync tree
      - add_ssh_keys:
          fingerprints:
            - "3a:45:11:f4:4a:89:7c:8f:ad:85:a0:7f:88:7a:ba:b7"
      - run:
          name: Fix ssh Could not resolve hostname
          command: ssh-keyscan 101.32.221.189 >> ~/.ssh/known_hosts
      - run:
          name: Tree
          command: ls
      - run:
          name: Deploy Over SSH
          command: rsync -av --delete dist/ $SSH_USER@$SSH_IP:/root/caddy/com/dist/
      - run:
          name: Reload Caddy
          command: |
            cd ~/caddy/wiki
            caddy reload
