version: 2.1

orbs:
  node: circleci/node@4.1
  codecov: codecov/codecov@3.2.3


jobs:
  build:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - codecov/upload
      - run: echo VITE_BUILD_BRANCH = ${CIRCLE_BRANCH} > .env
      - run: echo VITE_BUILD_HASH = ${CIRCLE_SHA1} > .env
      - run: cat .env
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - run:
          name: Compress Artifacts
          command: zip -r build.zip /dist
      - store_artifacts: 
          path: build.zip
          destination: build.zip

workflows:
  build:
    jobs:
      - build 