workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

version: 2.1
orbs:
  node: circleci/node@4.1
  slack: circleci/slack@4.10.1

jobs:
  build:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - run: echo VITE_BUILD_BRANCH = ${CIRCLE_BRANCH} > .env
      - run: echo VITE_BUILD_HASH = ${CIRCLE_SHA1} >> .env
      - run: cat .env
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - run:
          name: Compress Artifacts
          command: zip -r build.zip ./dist
      - store_artifacts:
          path: build.zip
          destination: build.zip
      - save_cache:
          key: v1-dependencies-{{ checksum "./dist/index.html" }}
          paths:
            - ./dist
  deploy:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./dist/index.html" }}
            - v1-dependencies
      - run: sudo apt-get update && sudo apt-get install rsync
      - add_ssh_keys:
          fingerprints:
            - "3a:45:11:f4:4a:89:7c:8f:ad:85:a0:7f:88:7a:ba:b7"
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            rsync -avce ssh $SSH_USER@$SSH_IP:~/caddy/com/
